#!/bin/bash

echo "=========================================="
echo "Customer Risk Alert System — Test"
echo "=========================================="
echo ""

# Check if Flask is running
if ! curl -s http://localhost:8080/api/health > /dev/null 2>&1; then
    echo "❌ Flask is not running!"
    echo "   Start it with: cd backend && python main.py"
    exit 1
fi

echo "✅ Flask is running"
echo ""

echo "TEST 1: Check Customer Risk API"
echo "--------------------------------"
curl -s http://localhost:8080/api/customer-risk | python3 -m json.tool
echo ""
echo ""

echo "=========================================="
echo "Expected Response"
echo "=========================================="
echo ""
echo "If alerts exist:"
echo "  - date: (today's date)"
echo "  - alerts: array of risk objects"
echo "  - total: number of alerts"
echo ""
echo "Each alert should have:"
echo "  - company (string)"
echo "  - event (string)"
echo "  - risk_level (High/Medium)"
echo "  - risk_score (0-10)"
echo "  - why_it_matters (string)"
echo "  - recommended_action (string)"
echo "  - sources (array)"
echo ""
echo "If no alerts:"
echo "  - alerts: []"
echo "  - message: 'No digest available yet'"
echo ""
echo "=========================================="
echo "Next Steps"
echo "=========================================="
echo ""
echo "1. Go to http://localhost:8080"
echo "2. Look at TOP of dashboard"
echo "3. Verify customer risk alert section"
echo ""
echo "Expected UI:"
echo ""
echo "If HIGH RISK:"
echo "  🔴 Red card with alert details"
echo "  Company name and event"
echo "  Why it matters"
echo "  Recommended action"
echo ""
echo "If MEDIUM RISK:"
echo "  🟡 Amber card with alert details"
echo ""
echo "If NO RISK:"
echo "  🟢 Green card: 'No Immediate Customer Risk Detected'"
echo ""
echo "To trigger alerts:"
echo "  1. Run pipeline: python main.py --run-now"
echo "  2. Wait for completion"
echo "  3. Refresh dashboard"
echo "  4. Check for risk alerts at top"
echo ""
