#!/usr/bin/env python3
"""Quick test to verify PDF generation works."""

import sys
import os

# Add backend to path
sys.path.insert(0, os.path.dirname(__file__))

def test_weasyprint():
    """Test if weasyprint is available."""
    try:
        from weasyprint import HTML
        print("✓ weasyprint is installed")
        return True
    except ImportError as e:
        print(f"✗ weasyprint not available: {e}")
        return False


def test_pdf_generation():
    """Test basic PDF generation."""
    try:
        from weasyprint import HTML
        
        # Simple HTML test
        html_content = """
        <!DOCTYPE html>
        <html>
        <head><meta charset="UTF-8"></head>
        <body>
            <h1>Test PDF</h1>
            <p>This is a test PDF generated by weasyprint.</p>
        </body>
        </html>
        """
        
        pdf_bytes = HTML(string=html_content).write_pdf()
        
        if pdf_bytes and len(pdf_bytes) > 0:
            print(f"✓ PDF generation works ({len(pdf_bytes)} bytes)")
            return True
        else:
            print("✗ PDF generation failed - empty output")
            return False
            
    except Exception as e:
        print(f"✗ PDF generation error: {e}")
        return False


def test_template_exists():
    """Check if PDF template exists."""
    template_path = os.path.join(os.path.dirname(__file__), "templates", "pdf_report.html")
    if os.path.exists(template_path):
        print(f"✓ PDF template exists")
        return True
    else:
        print(f"✗ PDF template not found at {template_path}")
        return False


def main():
    """Run all tests."""
    print("=" * 60)
    print("PDF Generation Test")
    print("=" * 60)
    
    results = [
        test_weasyprint(),
        test_pdf_generation(),
        test_template_exists(),
    ]
    
    print("\n" + "=" * 60)
    if all(results):
        print("✅ All tests passed! PDF export is ready.")
        print("\nNext: Restart your backend server")
        print("  cd backend")
        print("  source venv/bin/activate")
        print("  python main.py")
    else:
        print("❌ Some tests failed.")
        sys.exit(1)
    print("=" * 60)


if __name__ == "__main__":
    main()
