import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, ChevronDown, ChevronUp, Download } from "lucide-react";
import { API_BASE } from "@/lib/api";

interface Solution {
  title: string;
  what: string;
  how: string;
  impact: string;
  effort: "low" | "medium" | "high";
  priority: "quick win" | "core feature" | "bold move";
  target_user: "admin" | "teacher" | "student" | "district";
}

interface PainPointCardProps {
  issue: string;
  context: string;
  sources?: Array<{ source_name: string; url?: string }>;
  index: number;
}

export function PainPointCard({ issue, context, sources, index }: PainPointCardProps) {
  const [solutions, setSolutions] = useState<Solution[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasLoaded, setHasLoaded] = useState(false);

  const loadSolutions = async () => {
    // Toggle: if already open and loaded, just close
    if (isOpen && hasLoaded) {
      setIsOpen(false);
      return;
    }

    // If already loaded, just open
    if (hasLoaded) {
      setIsOpen(true);
      return;
    }

    // Load solutions
    setIsLoading(true);
    setIsOpen(true);
    setError(null);

    try {
      const sourceName = sources?.[0]?.source_name || "EdTech sources";
      const res = await fetch(`${API_BASE}/solutions`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          pain_point: issue,
          description: context,
          source: sourceName,
        }),
      });

      const data = await res.json();

      if (data.error || !data.solutions?.length) {
        setError(data.error || "No solutions generated. Try again.");
        return;
      }

      setSolutions(data.solutions);
      setHasLoaded(true);
    } catch (err) {
      setError("Network error. Is Flask running?");
    } finally {
      setIsLoading(false);
    }
  };

  const exportSolutions = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    const rows = solutions
      .map(
        (s, i) => `
      <tr>
        <td>${i + 1}</td>
        <td><strong>${s.title}</strong></td>
        <td>${s.priority}</td>
        <td>${s.effort}</td>
        <td>${s.target_user}</td>
        <td>${s.what}</td>
        <td>${s.impact}</td>
      </tr>`
      )
      .join("");

    printWindow.document.write(`
      <!DOCTYPE html><html><head>
      <title>Solutions — ${issue}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 2cm; font-size: 12px; }
        h1   { font-size: 16px; margin-bottom: 4px; }
        p    { color: #6b7280; margin: 0 0 20px; font-size: 11px; }
        table{ width: 100%; border-collapse: collapse; }
        th   { background: #f3f4f6; font-size: 10px; text-transform: uppercase;
               letter-spacing: .04em; padding: 8px; text-align: left;
               border-bottom: 2px solid #e5e7eb; }
        td   { padding: 8px; border-bottom: 1px solid #f3f4f6;
               font-size: 11px; vertical-align: top; }
        footer { margin-top: 24px; font-size: 10px; color: #9ca3af; }
      </style></head><body>
      <h1>Campus Cortex AI — Solution Roadmap</h1>
      <p>Pain point: ${issue} &nbsp;|&nbsp;
         Generated by MorningPulse AI &nbsp;|&nbsp;
         ${new Date().toLocaleDateString("en-IN", {
           day: "numeric",
           month: "long",
           year: "numeric",
         })}</p>
      <table>
        <thead>
          <tr>
            <th>#</th><th>Solution</th><th>Priority</th>
            <th>Effort</th><th>For</th><th>What it does</th><th>Impact</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <footer>MorningPulse AI — Campus Cortex AI Strategic Intelligence</footer>
      </body></html>`);

    printWindow.document.close();
    printWindow.print();
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "quick win":
        return "bg-green-100 text-green-800 border-green-200 dark:bg-green-950 dark:text-green-300 dark:border-green-800";
      case "core feature":
        return "bg-blue-100 text-blue-800 border-blue-200 dark:bg-blue-950 dark:text-blue-300 dark:border-blue-800";
      case "bold move":
        return "bg-purple-100 text-purple-800 border-purple-200 dark:bg-purple-950 dark:text-purple-300 dark:border-purple-800";
      default:
        return "bg-gray-100 text-gray-800 border-gray-200 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-700";
    }
  };

  const getEffortColor = (effort: string) => {
    switch (effort) {
      case "low":
        return "text-green-600 dark:text-green-400";
      case "medium":
        return "text-amber-600 dark:text-amber-400";
      case "high":
        return "text-red-600 dark:text-red-400";
      default:
        return "text-gray-600 dark:text-gray-400";
    }
  };

  return (
    <li className="flex flex-col gap-4 px-5 py-4 transition-colors hover:bg-muted/50">
      <div className="flex items-start gap-4">
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-foreground">{issue}</p>
          <p className="mt-1 text-xs text-muted-foreground">{context}</p>
          {sources && sources.length > 0 && (
            <div className="mt-2 flex flex-wrap gap-2">
              {sources.map((source, idx) =>
                source.url && source.url !== "#" && source.url !== "N/A" ? (
                  <a
                    key={idx}
                    href={source.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs text-primary underline hover:text-primary/80"
                  >
                    {source.source_name}
                  </a>
                ) : (
                  <span key={idx} className="text-xs text-muted-foreground">
                    {source.source_name}
                  </span>
                )
              )}
            </div>
          )}
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={loadSolutions}
          disabled={isLoading}
          className="shrink-0 text-xs"
        >
          {isLoading ? (
            <>
              <Loader2 className="mr-1 h-3 w-3 animate-spin" />
              Loading...
            </>
          ) : isOpen ? (
            <>
              <ChevronUp className="mr-1 h-3 w-3" />
              Hide solutions
            </>
          ) : (
            <>
              <ChevronDown className="mr-1 h-3 w-3" />
              View solutions
            </>
          )}
        </Button>
      </div>

      {/* Solutions Panel */}
      {isOpen && (
        <div className="border-t border-border pt-4">
          {isLoading && (
            <div className="flex items-center gap-2 py-4 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span>Generating solutions with AI...</span>
            </div>
          )}

          {error && (
            <div className="rounded-md border border-destructive/50 bg-destructive/10 p-3">
              <p className="text-sm text-destructive">{error}</p>
            </div>
          )}

          {!isLoading && !error && solutions.length > 0 && (
            <div className="space-y-3">
              <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                AI-Generated Solutions for Campus Cortex AI
              </p>

              {solutions.map((solution, idx) => (
                <div
                  key={idx}
                  className="rounded-lg border border-border bg-card p-4 shadow-sm transition-shadow hover:shadow-md"
                >
                  <div className="mb-2 flex items-start justify-between gap-2">
                    <div className="flex flex-wrap gap-1.5">
                      <Badge
                        variant="outline"
                        className={`text-[10px] font-semibold uppercase ${getPriorityColor(solution.priority)}`}
                      >
                        {solution.priority}
                      </Badge>
                      <Badge variant="secondary" className="text-[10px]">
                        For: {solution.target_user}
                      </Badge>
                    </div>
                    <span className={`text-[10px] font-medium ${getEffortColor(solution.effort)}`}>
                      {solution.effort} effort
                    </span>
                  </div>

                  <p className="mb-2 text-sm font-semibold text-foreground">
                    {idx + 1}. {solution.title}
                  </p>

                  <div className="space-y-1 text-xs text-muted-foreground">
                    <p>
                      <span className="font-medium text-foreground">What:</span> {solution.what}
                    </p>
                    <p>
                      <span className="font-medium text-foreground">How:</span> {solution.how}
                    </p>
                    <p>
                      <span className="font-medium text-foreground">Impact:</span> {solution.impact}
                    </p>
                  </div>
                </div>
              ))}

              <Button
                variant="outline"
                size="sm"
                onClick={exportSolutions}
                className="w-full text-xs"
              >
                <Download className="mr-2 h-3 w-3" />
                Download as PDF report
              </Button>
            </div>
          )}
        </div>
      )}
    </li>
  );
}
