/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarroomRouteImport } from './routes/warroom'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as IndexRouteImport } from './routes/index'

const WarroomRoute = WarroomRouteImport.update({
  id: '/warroom',
  path: '/warroom',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/linkedin': typeof LinkedinRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/trends': typeof TrendsRoute
  '/warroom': typeof WarroomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/linkedin': typeof LinkedinRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/trends': typeof TrendsRoute
  '/warroom': typeof WarroomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/linkedin': typeof LinkedinRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/trends': typeof TrendsRoute
  '/warroom': typeof WarroomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/linkedin'
    | '/settings'
    | '/sources'
    | '/trends'
    | '/warroom'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/linkedin' | '/settings' | '/sources' | '/trends' | '/warroom'
  id:
    | '__root__'
    | '/'
    | '/linkedin'
    | '/settings'
    | '/sources'
    | '/trends'
    | '/warroom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinkedinRoute: typeof LinkedinRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  TrendsRoute: typeof TrendsRoute
  WarroomRoute: typeof WarroomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warroom': {
      id: '/warroom'
      path: '/warroom'
      fullPath: '/warroom'
      preLoaderRoute: typeof WarroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinkedinRoute: LinkedinRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  TrendsRoute: TrendsRoute,
  WarroomRoute: WarroomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
